name: MainCI

on:
  push:
    branches-ignore:
    - fuzz*
    - mock*
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    
    - name: Install Rust components
      run: rustup component add rustfmt && rustup component add clippy
    - name: Install moleculec
      run: |
        export MOLC_VERSION=$(cat deps/godwoken-scripts/c/Makefile | egrep "MOLC_VERSION :=" | awk '{print $3}')
        test "$(moleculec --version)" = "Moleculec $MOLC_VERSION" \
        || CARGO_TARGET_DIR=target/ cargo install moleculec --version $MOLC_VERSION
    - name: Install ckb-cli
      run: which ckb-cli || CARGO_TARGET_DIR=target/ cargo install ckb-cli --version 0.43.0

    - name: Validate the checksum of SudtERC20Proxy Contract.bin
      run: make contract/sudt-erc20-proxy
        
    - name: Run Integration-Test
      run: bash devtools/ci/integration-test.sh

    - name: Checksums of generator and validator
      run: sha256sum build/generator build/generator_log build/validator build/validator_log
